In [1]:
import nashpy as nash
import numpy as np
from scipy.optimize import linprog
from scipy.optimize import minimize

In [2]:
A = np.array([
    [300, 280, 230],
    [200, 180, 130],
    [240, 380, 400],
])

B = np.array([
    [180, 110, 240],
    [120, 160, 210],
    [300, 140, 250],
])

In [13]:
A.max(axis=0).min()

300

In [17]:
B.max(axis=1).min()

210

In [3]:
game = nash.Game(A, B)
list(game.support_enumeration())

[(array([0.45454545, 0.        , 0.54545455]),
  array([0.73913043, 0.        , 0.26086957]))]

In [4]:
s = np.array([0.45, 0, 0.55, 0.74, 0, 0.26])

In [5]:
def l(x):
    p = x[:3]
    q = x[3:]
    
    As = p.dot(A).dot(q)
    Bs = p.dot(B).dot(q)
    
    return As.sum() + Bs.sum()

l(s)

527.56

In [6]:
def c1(x):
    p = x[:3]
    q = x[3:]
    
    return p.sum() - 1

c1(s)

0.0

In [7]:
def c2(x):
    p = x[:3]
    q = x[3:]
    
    return q.sum() - 1

c2(s)

0.0

In [8]:
def c3(x):
    p = x[:3]
    q = x[3:]
    
    Va = A.dot(q)
    As = p.dot(A).dot(q).sum()
    
    return As - Va

c3(s)

array([-1.100e-01,  9.989e+01,  9.000e-02])

In [9]:
def c4(x):
    p = x[:3]
    q = x[3:]
    
    Vb = p.dot(B)
    Bs = p.dot(B).dot(q).sum()
    
    return Bs - Vb

c4(s)

array([ -0.13, 119.37,   0.37])

In [10]:
constraints = [
    {'type': 'eq', 'fun': c1},
    {'type': 'eq', 'fun': c2},
    {'type': 'ineq', 'fun': c3},
    {'type': 'ineq', 'fun': c4},
]

bounds = [
    (0, 1),
    (0, 1),
    (0, 1),
    (0, 1),
    (0, 1),
    (0, 1),
]

x0 = [0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
solution = minimize(lambda x: -l(x), x0, method='SLSQP', constraints=constraints, bounds=bounds)
print(solution)

     fun: -527.1936758811916
     jac: array([-477.39131165, -325.2173996 , -568.69566345, -512.72727966,
       -460.90909576, -568.18182373])
 message: 'Optimization terminated successfully'
    nfev: 43
     nit: 6
    njev: 6
  status: 0
 success: True
       x: array([4.54545454e-01, 4.54248837e-11, 5.45454546e-01, 7.39130435e-01,
       5.85234505e-11, 2.60869565e-01])


In [11]:
s = solution.x

c1(s), c2(s), c3(s), c4(s)

(0.0,
 0.0,
 array([-1.1428483e-08,  1.0000000e+02,  1.1958150e-09]),
 array([-8.84867291e-09,  1.19090909e+02, -1.64553171e-09]))