In [2]:
import numpy as np

In [4]:
x = np.array([
    [11, 30],
    [17, 20]
])
y = np.array([100, 130])
y2 = np.array([200, 130])
n = x.shape[0]

In [5]:
xx = x.sum(axis=1) + y
xx

array([141, 167])

In [6]:
e = np.eye(n)
e

array([[1., 0.],
       [0., 1.]])

In [7]:
a = x / xx
a

array([[0.07801418, 0.17964072],
       [0.12056738, 0.11976048]])

In [8]:
ea = e - a

In [9]:
s = np.linalg.inv(ea)
s

array([[1.11435484, 0.22741935],
       [0.15263441, 1.1672043 ]])

In [10]:
(s > 0).all()

True

In [31]:
eig = np.linalg.eig(a)
d = eig[0]
v = eig[1]
v

array([[-0.81490278, -0.72730684],
       [ 0.57959767, -0.68631243]])

In [30]:
di = np.argmax(d)
d[di], v[:, di]

(0.2475295138840824, array([-0.72730684, -0.68631243]))

In [12]:
x1 = s.dot(y)
x1

array([141., 167.])

In [32]:
x2 = s.dot(y2)
x2

array([252.43548387, 182.26344086])

In [14]:
x2 - (a * x2).sum(axis=0)

array([202.30645161, 127.69354839])

In [15]:
a[0, 0] * x2[0] + a[1, 0] * x2[0]

50.12903225806451

In [16]:
a.tolist()

[[0.07801418439716312, 0.17964071856287425],
 [0.12056737588652482, 0.11976047904191617]]