In [1]:
pip install nashpy

  Attempting uninstall: numpy
    Found existing installation: numpy 1.20.1
    Uninstalling numpy-1.20.1:
      Successfully uninstalled numpy-1.20.1
Note: you may need to restart the kernel to use updated packages.


In [3]:
import nashpy as nash
import numpy as np

In [4]:
A = np.array([
    [300, 280, 230],
    [200, 180, 130],
    [240, 380, 400]
]) # A is the row player
game1 = nash.Game(A)

In [5]:
x, y = list(game1.support_enumeration())[0]

In [6]:
game1

Zero sum game with payoff matrices:

Row player:
[[300 280 230]
 [200 180 130]
 [240 380 400]]

Column player:
[[-300 -280 -230]
 [-200 -180 -130]
 [-240 -380 -400]]

In [7]:
from numpy import linalg
import numpy as np

In [8]:
linalg.solve(A, np.array([1, 1, 1]))

array([-0.01060606,  0.03484848, -0.02424242])

In [9]:
from scipy.optimize import linprog

In [10]:
c = [-1, -1, -1]
b = [1, 1, 1]

res = linprog(c, A_ub=A, b_ub=b)
1 / res.x.sum()

281.7388974857686