In [1]:
import numpy as np
from scipy.optimize import linprog

In [2]:
n = 4

In [3]:
a = np.array([
    [50, 30, 35, 45],
    [40, 40, 55, 40],
    [35, 40, 45, 55],
    [10, 20, 25, 35]
])

w = np.array([0.15, 0.25, 0.5, 0.1])

In [4]:
pi = 1 / n

In [5]:
w1 = np.ones(4) / n
a.dot(w1).max()

43.75

In [6]:
a.dot(w).max()

47.5

In [8]:
A = a * w
A = A.T

In [10]:
A.min(axis=0).max()

5.25

In [8]:
c = np.array([1, 1, 1, 1])
b = np.array([1, 1, 1, 1])

In [14]:
res = linprog(c, A_ub=-A, b_ub=-b)
res

     con: array([], dtype=float64)
     fun: 0.18439716891277014
 message: 'Optimization terminated successfully.'
     nit: 6
   slack: array([2.63421405e-08, 8.08510687e-01, 3.07801431e+00, 2.37843998e-08])
  status: 0
 success: True
       x: array([1.41843973e-02, 2.97140855e-09, 1.70212767e-01, 1.74916195e-09])

In [18]:
v = 1 / res.x.sum()
v

5.423076752729616

In [16]:
A.dot(res.x)

array([1.00000003, 1.80851069, 4.07801431, 1.00000002])

In [19]:
p = res.x / res.x.sum()
p

array([7.69230751e-02, 1.61141767e-08, 9.23076899e-01, 9.48583950e-09])

In [21]:
a.dot(p)

array([36.15384614, 53.84615349, 44.23076926, 23.84615389])

In [22]:
A.dot(p)

array([ 5.4230769 ,  9.80769226, 22.11538461,  5.42307688])