In [1]:
from sympy import *
from scipy.optimize import minimize
import numpy as np

In [2]:
a = sympify('1 + x_1 + y')

In [3]:
list(a.free_symbols)[0].name

'x_1'

In [13]:
f = sympify('x + 1 + y')
g = sympify('y + 12')

In [14]:
f.subs({'x': g})

2*y + 13

In [8]:
f.subs({'z': 2})

x + y + 1

In [9]:
c = sympify('k*q_1**2 + l*q_1*q_2 + m*q_2**2 + n')
q_1 = sympify('a + b*p_1')

In [15]:
c.free_symbols

{k, l, m, n, q_1, q_2}

In [18]:
c.subs({Symbol('q_1'): 2.0})

4.0*k + 2.0*l*q_2 + m*q_2**2 + n

In [19]:
s = sympify('p_1*(80.0 - 2.0*p_1) + p_2*(58.0 - 1.0*p_2) - 12800.0*(1 - 0.025*p_1)**2 - 10092.0*(1 - 0.0172413793103448*p_2)**2 - 5.0*(58.0 - 1.0*p_2)*(80.0 - 2.0*p_1) - 7.0')

In [21]:
simplify(s)

-10.0*p_1**2 - 10.0*p_1*p_2 + 1300.0*p_1 - 3.99999999999999*p_2**2 + 805.999999999999*p_2 - 46099.0

In [26]:
l = lambdify(symbols('p_1 p_2'), s)

In [44]:
minimize(lambda args: -l(*args), np.zeros(2))

      fun: -206.9999999999951
 hess_inv: array([[ 0.53333571, -0.33330999],
       [-0.33330999,  0.33341576]])
      jac: array([-3.81469727e-06, -7.62939453e-06])
  message: 'Optimization terminated successfully.'
     nfev: 18
      nit: 5
     njev: 6
   status: 0
  success: True
        x: array([2.00000001, 5.99999889])

In [54]:
s = sympify('-2.5 * x^2 - 5 * x * y - 4 * y^2 + 40 * x + 58 * y - 7')
l = lambdify(symbols('x y'), s)
r = minimize(lambda args: -l(*args), np.array([0.5, 0.5]))
r.x

array([1.99999969, 6.00000027])

In [53]:
s = sympify('p_1*(80.0 - 2.0*p_1) + p_2*(58.0 - 1.0*p_2) - 12800.0*(1 - 0.025*p_1)**2 - 10092.0*(1 - 0.0172413793103448*p_2)**2 - 5.0*(58.0 - 1.0*p_2)*(80.0 - 2.0*p_1) - 7.0')
l = lambdify(symbols('p_1 p_2'), s)
r = minimize(lambda args: -l(*args), np.zeros(2))
r

      fun: -206.99999999999326
 hess_inv: array([[ 0.13333321, -0.16666647],
       [-0.16666647,  0.33333304]])
      jac: array([-5.7220459e-06, -5.7220459e-06])
  message: 'Optimization terminated successfully.'
     nfev: 27
      nit: 5
     njev: 9
   status: 0
  success: True
        x: array([38.99999904, 52.00000136])

In [6]:
np.linspace(1, 4, 4)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [8]:
np.outer(np.linspace(1, 4, 4), np.ones(4))

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [9]:
np.outer(np.linspace(1, 4, 4), np.ones(4)).T

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])